# Generated by Django 5.1.4 on 2025-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(default='teste'),
        ),
    ]
