# Generated by Django 5.1.4 on 2025-01-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadet', '0002_alter_cadet_created_at_alter_cadet_updated_at'),
        ('certificate', '0002_certificate_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills_required',
            field=models.ManyToManyField(related_name='certificates', to='certificate.skill'),
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='certificate.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='cadet.cadet')),
            ],
        ),
    ]
