# Generated by Django 5.1.4 on 2025-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_skill_remove_certificate_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='skills_required',
            field=models.ManyToManyField(to='certificate.skill'),
        ),
    ]
