# Generated by Django 5.1.4 on 2025-01-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadet', '0003_remove_cadet_role_id_cadet_role_id'),
        ('certificate', '0004_alter_certificate_skills_required'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Requirements',
        ),
        migrations.RenameModel(
            old_name='UserSkill',
            new_name='UserRequirements',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='skills_required',
            new_name='requirements_required',
        ),
        migrations.RenameField(
            model_name='userrequirements',
            old_name='skill',
            new_name='requirements',
        ),
    ]
