# Generated by Django 5.1.4 on 2025-01-15 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadet', '0004_article'),
        ('certificate', '0006_route_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificatepdf', to='cadet.cadet')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificatepdf', to='certificate.certificate')),
            ],
        ),
    ]
